<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-05-13 13:15
=======
# Generated by Django 2.2 on 2020-05-18 09:37
>>>>>>> sus_working_cart

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default=' ', max_length=50)),
                ('courseDesc', models.TextField(default=' ')),
                ('longDesc', models.TextField(default=' ')),
                ('courseImage', models.ImageField(default=' ', upload_to='pics2/')),
                ('price', models.IntegerField(default='100')),
<<<<<<< HEAD
                ('teacher', models.CharField(default=' ', max_length=50)),
=======
                ('bought', models.BooleanField(default=True)),
>>>>>>> sus_working_cart
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(default=' ', max_length=50)),
                ('moduleNum', models.IntegerField(default=0)),
                ('disc', models.TextField(default=' ', max_length=300)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='studyMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=' ', max_length=50)),
                ('typ', models.CharField(choices=[('video', 'video'), ('pdf', 'pdf'), ('doc', 'doc')], default='video', max_length=6)),
                ('file1', models.FileField(default=' ', upload_to='files12/')),
                ('desc', models.TextField(default=' ', max_length=300)),
                ('fileNo', models.IntegerField(default=0)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module')),
            ],
        ),
        migrations.CreateModel(
            name='student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('courses', models.ManyToManyField(blank=True, to='home.Course')),
                ('user1', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(default=' ', max_length=50)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('courses', models.ManyToManyField(blank=True, to='home.Course')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='home.student1')),
=======
                ('ques', models.CharField(default=' ', max_length=100)),
                ('option1', models.CharField(default=' ', max_length=50)),
                ('option2', models.CharField(default=' ', max_length=50)),
                ('option3', models.CharField(default=' ', max_length=50)),
                ('option4', models.CharField(default=' ', max_length=50)),
                ('correctoption', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default=models.CharField(default=' ', max_length=50), max_length=50)),
                ('quizName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
>>>>>>> sus_working_cart
            ],
        ),
    ]
