<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-05-13 13:15

from django.conf import settings
import django.contrib.auth.models
=======
# Generated by Django 3.0.5 on 2020-05-13 13:07

>>>>>>> aaaaa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0011_update_proxy_permissions'),
=======
>>>>>>> aaaaa
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(default=' ', max_length=50)),
                ('courseDesc', models.TextField(default=' ')),
                ('courseImage', models.ImageField(default=' ', upload_to='pics2/')),
                ('price', models.IntegerField(default='100')),
                ('bought', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('img', models.ImageField(default=' ', upload_to='pics2/')),
                ('desc', models.TextField(default=' ')),
                ('price', models.IntegerField(default='100')),
                ('bought', models.BooleanField(default=True)),
                ('destno', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=50)),
                ('ans1', models.CharField(max_length=50)),
                ('ans2', models.CharField(max_length=50)),
                ('ans3', models.CharField(max_length=50)),
                ('ans4', models.CharField(max_length=50)),
                ('correct', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('correctAnswer', models.CharField(max_length=50)),
                ('totalPoints', models.CharField(max_length=50)),
                ('quizDate', models.DateField(max_length=50)),
                ('quizTime', models.CharField(max_length=50)),
                ('stuEmail', models.CharField(max_length=50)),
                ('totalQues', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('attempts', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sub', models.CharField(default=' ', max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudyFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherEmail', models.CharField(max_length=50)),
                ('folderName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dateofBirth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(blank=True, to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(default=' ', max_length=50)),
                ('file1', models.FileField(default=' ', upload_to='files12/')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
=======
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(default=' ', max_length=50)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='studyMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=' ', max_length=50)),
                ('typ', models.CharField(choices=[('video', 'video'), ('pdf', 'pdf'), ('doc', 'doc')], default='video', max_length=6)),
                ('file1', models.FileField(default=' ', upload_to='files12/')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(default=' ', max_length=50)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(default=' ', max_length=100)),
                ('option1', models.CharField(default=' ', max_length=50)),
                ('option2', models.CharField(default=' ', max_length=50)),
                ('option3', models.CharField(default=' ', max_length=50)),
                ('option4', models.CharField(default=' ', max_length=50)),
                ('correctoption', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default=models.CharField(default=' ', max_length=50), max_length=50)),
                ('quizName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
>>>>>>> aaaaa
            ],
        ),
    ]
