# Generated by Django 3.0.5 on 2020-05-21 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 21, 23, 8, 16, 852354)),
        ),
    ]
