# Generated by Django 3.0.5 on 2020-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=' ', upload_to='pics2'),
        ),
    ]
