# Generated by Django 3.0.5 on 2020-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='longDesc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='module',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moduleNum',
        ),
        migrations.RemoveField(
            model_name='studymat',
            name='module',
        ),
        migrations.AddField(
            model_name='studymat',
            name='Title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
