# Generated by Django 3.0.5 on 2020-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200513_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='longDesc',
            field=models.TextField(default=' '),
        ),
    ]
