# Generated by Django 2.2 on 2020-05-22 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200521_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 22, 6, 41, 53, 811350)),
        ),
    ]
