# Generated by Django 3.0.5 on 2020-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student1_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student1',
            name='courses',
            field=models.ManyToManyField(blank=True, to='home.Course'),
        ),
    ]
