# Generated by Django 3.0.5 on 2020-06-03 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200522_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 3, 17, 49, 15, 218813)),
        ),
    ]
