# Generated by Django 3.0.5 on 2020-05-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file1',
            field=models.FileField(default=' ', upload_to='files12/'),
        ),
    ]
