# Generated by Django 3.0.5 on 2020-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
