# Generated by Django 3.0.5 on 2020-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course_longdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
