# Generated by Django 3.0.5 on 2020-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moduleNum',
            field=models.IntegerField(default=0),
        ),
    ]
