# Generated by Django 3.0.5 on 2020-05-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200514_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctoption',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default=models.CharField(default=' ', max_length=50), max_length=50),
        ),
    ]
