# Generated by Django 3.0.5 on 2020-05-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_question_correctoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
    ]
