# Generated by Django 3.0.5 on 2020-05-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0006_remove_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(default=' ', max_length=100)),
                ('option1', models.CharField(default=' ', max_length=50)),
                ('option2', models.CharField(default=' ', max_length=50)),
                ('option3', models.CharField(default=' ', max_length=50)),
                ('option4', models.CharField(default=' ', max_length=50)),
                ('correctoption', models.CharField(choices=[(models.CharField(default=' ', max_length=50), models.CharField(default=' ', max_length=50)), (models.CharField(default=' ', max_length=50), models.CharField(default=' ', max_length=50)), (models.CharField(default=' ', max_length=50), models.CharField(default=' ', max_length=50)), (models.CharField(default=' ', max_length=50), models.CharField(default=' ', max_length=50))], default=models.CharField(default=' ', max_length=50), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='studyMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default=' ', max_length=50)),
                ('typ', models.CharField(choices=[('video', 'video'), ('pdf', 'pdf'), ('doc', 'doc')], default='video', max_length=6)),
                ('file1', models.FileField(default=' ', upload_to='files12/')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.DeleteModel(
            name='ReadyQuiz',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudyFolder',
        ),
        migrations.RemoveField(
            model_name='module',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='points',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizName',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.DeleteModel(
            name='stud',
        ),
        migrations.AddField(
            model_name='studymat',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Module'),
        ),
        migrations.AddField(
            model_name='question',
            name='quizName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.quiz'),
        ),
    ]
