# Generated by Django 3.0.5 on 2020-05-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_quiz_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=0)),
                ('totalQues', models.IntegerField(default=0)),
                ('correctAns', models.IntegerField(default=0)),
                ('percentScore', models.FloatField(default=0.0)),
                ('quiz', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
            ],
        ),
    ]
