# Generated by Django 3.0.5 on 2020-05-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studymat_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymat',
            name='module',
        ),
    ]
