# Generated by Django 3.0.5 on 2020-05-18 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_scorecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='time',
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 19, 0, 26, 28, 286665)),
        ),
    ]
