# Generated by Django 3.0.5 on 2020-05-19 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200519_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 20, 0, 31, 5, 417147)),
        ),
    ]
