# Generated by Django 3.0.5 on 2020-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_scorecard_percentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='percentScore',
            field=models.FloatField(default=0.0),
        ),
    ]
