# Generated by Django 3.0.5 on 2020-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_studymat_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymat',
            name='file1',
            field=models.FileField(default=' ', upload_to='files12/'),
        ),
    ]
