# Generated by Django 3.0.5 on 2020-05-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_scorecard_percentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.student1'),
        ),
    ]
