# Generated by Django 3.0.5 on 2020-05-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_studymat_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymat',
            name='desc',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
