# Generated by Django 3.0.5 on 2020-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dateofBirth', models.DateField()),
            ],
        ),
    ]
