# Generated by Django 3.0.5 on 2020-05-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_student_courses'),
        ('Login_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses1',
            field=models.ManyToManyField(blank=True, to='home.Course'),
        ),
    ]
